# This is a basic workflow to help you get started with Actions

name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Run make install
        run: make install

      - name: Run make lint
        run: make lint
